name: Deploy Beta Packages

on:
  push:
    branches:
      - develop

jobs:
  deploy-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Install Dependencies
        run: pnpm install

      - name: Check
        run: |
          pnpm -r check:prettier
          pnpm -r check:eslint

      #      - name: Test
      #        run: |
      #          pnpm exec playwright install chromium
      #          pnpm -r test

      - name: Gitversion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

      - name: Build
        run: |
          pnpm -r copy
          pnpm -F './packages/**/*' build

      - name: Copy README
        run: cp ./README.md packages/react/xr

      - name: Set Version
        run: pnpm -F './packages/**/*' exec json -f "package.json" -I -e 'this.version = "${{ steps.gitversion.outputs.fullSemVer }}"'

      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"

      - id: check-pointer-events
        uses: PostHog/check-package-version@v2
        with:
          path: ./packages/pointer-events/

      - name: Deploy pointer events Package
        if: steps.check-pointer-events.outputs.is-new-version == 'true'
        working-directory: ./packages/pointer-events
        run: pnpm publish --access public --no-git-checks --tag alpha

      - id: check-handle-vanilla
        uses: PostHog/check-package-version@v2
        with:
          path: ./packages/handle/

      - name: Deploy Handle Vanilla Package
        if: steps.check-handle-vanilla.outputs.is-new-version == 'true'
        working-directory: ./packages/handle
        run: pnpm publish --access public --no-git-checks --tag alpha

      - id: check-xr-vanilla
        uses: PostHog/check-package-version@v2
        with:
          path: ./packages/xr/

      - name: Deploy XR Vanilla Package
        if: steps.check-xr-vanilla.outputs.is-new-version == 'true'
        working-directory: ./packages/xr
        run: pnpm publish --access public --no-git-checks --tag alpha

      - id: check-handle-react
        uses: PostHog/check-package-version@v2
        with:
          path: ./packages/react/handle/

      - name: Deploy Handle React Package
        if: steps.check-handle-react.outputs.is-new-version == 'true'
        working-directory: ./packages/react/handle
        run: pnpm publish --access public --no-git-checks --tag alpha

      - id: check-xr-react
        uses: PostHog/check-package-version@v2
        with:
          path: ./packages/react/xr/

      - name: Deploy XR React Package
        if: steps.check-xr-react.outputs.is-new-version == 'true'
        working-directory: ./packages/react/xr
        run: pnpm publish --access public --no-git-checks --tag alpha
